

[NoDelete]
interface Engine {
  //tvg::Initializer::init(tvg::CanvasEngine::Sw, 0);
  [Internal="thorvg_engine_init", Static] void init(int threadCount);
  [Internal="thorvg_engine_destroy", Static] void destroy();
};


[Internal="tvg::SwCanvas::Colorspace"]
enum ColorSpace {
    "CS_ABGR8888",
    "CS_ARGB8888",
    "CS_ABGR8888_STRAIGHT",
    "CS_ARGB8888_STRAIGHT"
};

[NoDelete,Internal="tvg::Shape"]
interface Shape {
  [Internal="createShape", Static,Const] Shape make();
  void moveTo(float x, float y); 
  void lineTo(float x, float y); 
  void appendRect(float x, float y, float width, float height, float rx, float ry);
  void fill(int r, int g, int b, int a); 
  void close();

};

[Internal="tvg::SwCanvas"]
interface Canvas {
  [Internal="createCanvas", Static] Canvas make();

  void target( [Cast="uint32_t *"]bytes buffer, int stride, int width, int height, ColorSpace colorSpace);
  [CObject, Internal="canvas_push_shape"] void pushShape( Shape s );
  void draw();
  void sync();
};

